"""add idempotency key and created at

Revision ID: 0bf1046be179
Revises: 62dce0f8a9de
Create Date: 2026-06-23 01:09:00.233316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bf1046be179'
down_revision: Union[str, Sequence[str], None] = '62dce0f8a9de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_applications', sa.Column('idempotency_key', sa.String(), nullable=False))
    op.add_column('loan_applications', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.create_unique_constraint(None, 'loan_applications', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_applications', sa.Column('status', postgresql.ENUM('DRAFT', 'SUBMITTED', name='loanstatus'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'loan_applications', type_='unique')
    op.drop_column('loan_applications', 'created_at')
    op.drop_column('loan_applications', 'idempotency_key')
    # ### end Alembic commands ###
