"""create loan application table

Revision ID: 62dce0f8a9de
Revises: 
Create Date: 2026-06-22 20:15:52.068132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62dce0f8a9de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', name='loanstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_applications')
    # ### end Alembic commands ###
